version: '3.8'
volumes: 
  db-data:

services:
  # WEB SERVER
  php-apache-environment:
    container_name: c19-dicotec
    build:
      context: ./
      dockerfile: Dockerfile
    image: c19-dicotec
    volumes:
      - ./src:/var/www/c19-dicotec
      - ./apache/c19-dicotec.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 80:80
    depends_on:
      - db
  # DATABASE    
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  # PHPMYADMIN
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    depends_on:
      - db
